name: Trading module CI

on:
  # Execute this pipeline when pushing to dev branch for path trading:
  push:
    branches:
      - "dev"
    paths:
      - 'trading/**'

  # Execute this pipeline from other workflows (deployment):
  workflow_call:

jobs:
  compile:
    name: Compile trading module ğŸ› ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Set up JDK 18 ğŸ—ï¸
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: maven

      - name: Compile code with maven ğŸ› ï¸
        working-directory: ./trading
        run: mvn compile

  test:
    name: Run tests in trading module ğŸ§ª
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Set up JDK 18 ğŸ—ï¸
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: maven

      - name: Run tests with maven ğŸ§ª
        working-directory: ./trading
        run: mvn test